# Generated by Django 4.2.19 on 2025-02-16 10:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DialysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('weight_before', models.FloatField(help_text='Weight before dialysis (kg)')),
                ('systolic_bp', models.IntegerField(help_text='Systolic Blood Pressure')),
                ('diastolic_bp', models.IntegerField(help_text='Diastolic Blood Pressure')),
                ('initial_drain_volume', models.IntegerField(help_text='Initial Drain Volume (ml)')),
                ('total_uf', models.IntegerField(help_text='Total UF (ml)')),
                ('avg_dwell', models.DurationField(help_text='Average Dwell Time (hh:mm)')),
                ('lost_dwell', models.DurationField(help_text='Lost Dwell Time (hh:mm)')),
                ('added_dwell', models.DurationField(help_text='Added Dwell Time (hh:mm)')),
                ('weight_after', models.FloatField(help_text='Weight after dialysis (kg)')),
                ('comments', models.TextField(blank=True, help_text='Additional comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
