# Generated by Django 4.2.19 on 2025-02-16 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialysisrecord',
            old_name='avg_dwell',
            new_name='average_dwell',
        ),
        migrations.RenameField(
            model_name='dialysisrecord',
            old_name='diastolic_bp',
            new_name='blood_pressure_diastolic',
        ),
        migrations.RenameField(
            model_name='dialysisrecord',
            old_name='systolic_bp',
            new_name='blood_pressure_systolic',
        ),
    ]
