# Generated by Django 4.2.19 on 2025-03-01 00:20

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_avg_dwell_dialysisrecord_average_dwell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialysisrecord',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
