# Generated by Django 4.2.19 on 2025-02-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
    ]
