# Generated by Django 4.2.19 on 2025-03-01 00:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_uploadedfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dzibrzlq9/image/upload/v1700000000/default.jpg', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
